# Generated by Django 6.0.1 on 2026-01-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogKeyword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blogs/covers/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('nation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('is_comments_enabled', models.BooleanField(default=True)),
                ('total_views', models.PositiveBigIntegerField(default=0)),
                ('total_likes', models.PositiveBigIntegerField(default=0)),
                ('total_comments', models.PositiveBigIntegerField(default=0)),
                ('total_bookmarks', models.PositiveBigIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(blank=True, related_name='blogs', to='blog.blogkeyword')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_blog_slug_d925e3_idx'), models.Index(fields=['status'], name='blog_blog_status_e6780b_idx'), models.Index(fields=['published_at'], name='blog_blog_publish_097daa_idx')],
            },
        ),
    ]
