# Generated by Django 6.0.1 on 2026-02-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_bg_color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
    ]
