# Generated by Django 5.2.5 on 2026-03-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_views_alter_bookmark_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='blog.blog')),
            ],
            options={
                'indexes': [models.Index(fields=['blog', 'session_key'], name='blog_blogvi_blog_id_14413e_idx'), models.Index(fields=['created_at'], name='blog_blogvi_created_d45b93_idx')],
            },
        ),
    ]
