# Generated by Django 5.2.5 on 2026-03-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='blogview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
